# basic numpy operations

### by the end of this session we will have a clear understanding on numpy arrays

#### Sessions Agenda


<ol>
  <li>Creating one dimensional numpy arrays</li>
  <li>Creating two dimensional numpy arrays</li>
  <li>Creating n dimensional numpy arrays</li>
  <li>Slicing in arrays</li>
  <li>Basic mathematical operations on numpy arrays</li>
</ol> 

## creating arrays

In [8]:
#importing numpy package
import numpy as np

#creating an array object
array1 = np.array([1,2,3]) #creating one ddimensional array

In [9]:
#to know the shape of the array
print("Shape of the 'array1' is:", array1.shape)
#to know the dimension of the array
print("dimension of the 'array1' is:", array1.ndim)
#to print the array
print("the array created is as follow:",array1)

Shape of the 'array1' is: (3,)
dimension of the 'array1' is: 1
the array created is as follow: [1 2 3]


In [10]:
#creating two dimensional array
array2 = np.array([[4,5,6],[7,8,9]])
print("Shape of the 'array2' is:", array2.shape)
#to know the dimension of the array
print("dimension of the 'array2' is:", array2.ndim)
#to print the array
print("the array created is as follow:",array2)

Shape of the 'array2' is: (2, 3)
dimension of the 'array2' is: 2
the array created is as follow: [[4 5 6]
 [7 8 9]]


#### creating empty numpy array

In [11]:
#creating an empty array
empty_array = np.array([])
print("Shape of the 'array2' is:", empty_array.shape)
#to know the dimension of the array
print("dimension of the 'array2' is:", empty_array.ndim)
#to print the array
print("the array created is as follow:",empty_array)

Shape of the 'array2' is: (0,)
dimension of the 'array2' is: 1
the array created is as follow: []


#### Creating array containing Zeros and ones

In [12]:
#creating array containing ZEROS
zero_array = np.zeros([3,3])
zero_array1 = np.zeros([3])
print(zero_array)
print("---------------")
print(zero_array1)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
---------------
[ 0.  0.  0.]


In [13]:
#creating array containing ONES
ones_array = np.ones([3,4])

#### Creating Array with random numbers

In [14]:
random_array = np.random.random([3,3])

In [15]:
random_array

array([[ 0.07775048,  0.17297101,  0.50941746],
       [ 0.18484254,  0.67343146,  0.52545008],
       [ 0.63073694,  0.06080708,  0.41330561]])

#### Performing few mathematical operations on arrays

In [16]:
angle_array = np.array([[0,30,45,90,],[90,45,30,0]])

In [17]:
print(np.sin(angle_array))

[[ 0.         -0.98803162  0.85090352  0.89399666]
 [ 0.89399666  0.85090352 -0.98803162  0.        ]]


In [4]:
array11 = np.array([20,25,60,40])
array12 = np.array([5,25,30,40])

#### Few basic mathematical operations on arrays

In [21]:
print("sum of array11 and array12 is:",np.add(array11,array12))
print("substraction of array11 and array12 is:", np.subtract(array11,array12))
print("division of array11 and array12 is:", np.divide(array11,array12))
print("remainder of array11 and array12 is:", np.remainder(array11,array12))

sum of array11 and array12 is: [25 50 90 80]
substraction of array11 and array12 is: [15  0 30  0]
division of array11 and array12 is: [ 4.  1.  2.  1.]
remainder of array11 and array12 is: [0 0 0 0]


In [20]:
print("square root of array11 is:", np.sqrt(array11))
print(" natural logarithms of array11 is:", np.log(array11))

square root of array11 is: [ 4.47213595  5.          7.74596669  6.32455532]
 natural logarithms of array11 is: [ 2.99573227  3.21887582  4.09434456  3.68887945]


#### array slicing...

In [25]:
slice_array = np.array([88,75,95,35,28,32,49])
print("print third third element in slice_array:", slice_array[2:3])
print("print second element to fifth element in slice_array:", slice_array[1:5])

print third third element in slice_array: [95]
print second element to fifth element in slice_array: [75 95 35 28]


In [33]:
slice_array1 = np.array([[1,3,2,9,4,7],[11,12,33,54,10,6]])
print(slice_array1[0][2:3])

[2]


#### basic statistical operations on arrays

In [36]:
print("mean of array slice_array :", np.mean(slice_array))
print("minimum value in the array, slice_array :", np.min(slice_array))
print("maximum value in the array, array slice_array :", np.max(slice_array))
print("standard deviation of array, slice_array :", np.std(slice_array))
print("variance of array, slice_array :", np.var(slice_array))

mean of array slice_array : 57.4285714286
minimum value in the array, slice_array : 28
maximum value in the array, array slice_array : 95
standard deviation of array, slice_array : 26.0266739155
variance of array, slice_array : 677.387755102


#### getting the mean of rows in n dimensional array

In [52]:
arr1 = np.random.random([3,4])
print(arr1)
print("////////////////////////////////////////////////////////////////////////////")
for row in arr1:
    print( row, "mean is:", np.mean(row))

[[ 0.48559357  0.10560822  0.16981272  0.55926584]
 [ 0.40194881  0.25966114  0.6193347   0.74096893]
 [ 0.77138518  0.77499489  0.12550847  0.49594039]]
////////////////////////////////////////////////////////////////////////////
[ 0.48559357  0.10560822  0.16981272  0.55926584] mean is: 0.33007008693
[ 0.40194881  0.25966114  0.6193347   0.74096893] mean is: 0.505478395708
[ 0.77138518  0.77499489  0.12550847  0.49594039] mean is: 0.541957232503


#### sorting numpy array

In [51]:
print("descending order of slice_array is:" ,-np.sort(-slice_array))
print("ascending order of slice_array:", np.sort(slice_array))

descending order of slice_array is: [95 88 75 49 35 32 28]
ascending order of slice_array: [28 32 35 49 75 88 95]


In [58]:
# sorting according to column
array2 = np.array(([55,27,98],[4,99,1],[98,74,0]))
print("array sorted according to column is :",np.sort(array2, axis=1))

array sorted according to column is : [[27 55 98]
 [ 1  4 99]
 [ 0 74 98]]


#### resizing an array and transpose

In [68]:
a1 = np.random.random([3,4])
a2 = a1.reshape((4,3))
print(a1)
print("after reshape")
print(a2)
print("transpose of a1 array is as follows")
print(np.transpose(a1))

[[ 0.9896091   0.89133444  0.51932705  0.24984199]
 [ 0.39812883  0.79540451  0.95127202  0.68282473]
 [ 0.96712839  0.69579003  0.54112704  0.6934753 ]]
after reshape
[[ 0.9896091   0.89133444  0.51932705]
 [ 0.24984199  0.39812883  0.79540451]
 [ 0.95127202  0.68282473  0.96712839]
 [ 0.69579003  0.54112704  0.6934753 ]]
transpose of a1 array is as follows
[[ 0.9896091   0.39812883  0.96712839]
 [ 0.89133444  0.79540451  0.69579003]
 [ 0.51932705  0.95127202  0.54112704]
 [ 0.24984199  0.68282473  0.6934753 ]]
